# Generated by Django 5.0.6 on 2024-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmoAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('google_link', models.CharField(max_length=1000)),
                ('long_term_token', models.CharField(max_length=2000)),
                ('lead_filter', models.CharField(max_length=1000)),
            ],
        ),
    ]
